#yml弥补xml数据标签太多而不重视数据的缺点
#英文冒号后面必须要有个空格,否则出错还不报错
#优先级没有properties高
server:
  port: 8081

spring:
  thymeleaf:
    cache: false #关闭缓存
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#    %2b 是 “+” 的转义，所以GMT%2b8即”GMT+8“这个北京时间
    url: jdbc:mysql://127.0.0.1:3306/tmp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
